#!/bin/sh -e

BIN_PATH="/usr/bin"
CONFIG_PATH="${HOME}/.config"

case ${CONFIG_DOTS_REPO} in "")
  echo "[FATAL] export CONFIG_DOTS_REPO to a dotfile repository and retry."
  exit 1
esac

go() {
  cd ${CONFIG_DOTS_REPO}

  printf "[linkie] pushing changes... "
  git add *
  if git commit -m "automatically updated by linkie" \
    > /dev/null 2>&1; then git push > /dev/null 2>&1; echo "done"; else
      echo "nothing to push"
  fi

  printf "[linkie] relinking... "

  for SYM in `find $PWD -maxdepth 1 -not -name "*.git*" -and -not -path "$PWD" | sed "s|$PWD||g"`; do
    ORIGIN="${CONFIG_DOTS_REPO}/${SYM}"; DEST="${CONFIG_PATH}/${SYM}"
    rm -rf ${DEST} || true; ln -sf ${ORIGIN} ${DEST} || { echo "failed at ${ORIGIN}" && exit 1; }
  done

  echo "done"
}

selfup() {
  su -c "ls -l ${BIN_PATH}/linkie && curl -L \
  https://github.com/draumaz/linkie/archive/refs/heads/main.tar.gz | \
    tar -xpzf - \
      --strip-components=1 \
      -C ${BIN_PATH} \
      linkie-main/linkie && ls -l ${BIN_PATH}/linkie"
}

case $1 in
  selfup) selfup ;;
  *) go ;;
esac
